# Generated by Django 5.2.13 on 2026-04-12 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MitreMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique_id', models.CharField(max_length=30)),
                ('technique_name', models.CharField(max_length=180)),
                ('tactic', models.CharField(max_length=120)),
                ('coverage_status', models.CharField(choices=[('covered', 'Covered'), ('critical', 'Critical'), ('planned', 'Planned')], default='covered', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitre_mappings', to='scenarios.scenario')),
            ],
            options={
                'ordering': ['technique_id'],
                'unique_together': {('scenario', 'technique_id')},
            },
        ),
    ]
