# Generated by Django 5.2.13 on 2026-06-13 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('time_taken', models.PositiveIntegerField(default=0, help_text='Time to complete the lab, in seconds')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the lab was completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lab Completion',
                'verbose_name_plural': 'Lab Completions',
                'ordering': ['-completed_at', '-id'],
            },
        ),
    ]
